/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import java.awt.event.ActionListener;

/**
 *
 * @author Dan
 */
public class AdminViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminView
     */
    public AdminViewPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void addButtonCreateCustomerListener(ActionListener buttonListener) {
        buttonCreateCustomer.addActionListener(buttonListener);
    }
    
    public void addButtonEditCustomerListener(ActionListener buttonListener) {
        buttonEditCustomer.addActionListener(buttonListener);
    }
    
     public void addButtonCreatePriceListener(ActionListener buttonListener) {
        buttonCreatePrice.addActionListener(buttonListener);
    }
     
      public void addButtonEditPricesListener(ActionListener buttonListener) {
        buttonEditPrices.addActionListener(buttonListener);
    }
      
       public void addButtonSeeTransactionsListener(ActionListener buttonListener) {
        buttonSeeTransactions.addActionListener(buttonListener);
    }
       
       public void addButtonLogOffListener(ActionListener buttonListener) {
        buttonLogOff.addActionListener(buttonListener);
    }
       
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonLogOff = new javax.swing.JButton();
        buttonCreateCustomer = new javax.swing.JButton();
        buttonEditCustomer = new javax.swing.JButton();
        buttonCreatePrice = new javax.swing.JButton();
        buttonEditPrices = new javax.swing.JButton();
        buttonSeeTransactions = new javax.swing.JButton();

        buttonLogOff.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        buttonLogOff.setText("Log off");
        buttonLogOff.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonCreateCustomer.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        buttonCreateCustomer.setText("Create customer");
        buttonCreateCustomer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonEditCustomer.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        buttonEditCustomer.setText("Edit customers");
        buttonEditCustomer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonCreatePrice.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        buttonCreatePrice.setText("Create price");
        buttonCreatePrice.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonEditPrices.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        buttonEditPrices.setText("Edit prices");
        buttonEditPrices.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonSeeTransactions.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        buttonSeeTransactions.setText("See transactions");
        buttonSeeTransactions.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonCreatePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonEditPrices, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonCreateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonEditCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonSeeTransactions, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(505, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonLogOff, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonLogOff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCreateCustomer)
                    .addComponent(buttonEditCustomer))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCreatePrice)
                    .addComponent(buttonEditPrices))
                .addGap(18, 18, 18)
                .addComponent(buttonSeeTransactions)
                .addContainerGap(293, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCreateCustomer;
    private javax.swing.JButton buttonCreatePrice;
    private javax.swing.JButton buttonEditCustomer;
    private javax.swing.JButton buttonEditPrices;
    private javax.swing.JButton buttonLogOff;
    private javax.swing.JButton buttonSeeTransactions;
    // End of variables declaration//GEN-END:variables
}
