/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Morten
 */
public class UserViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserViewPanel
     */
    public UserViewPanel() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void addButtonSeeUserAccountListener(ActionListener buttonListener) {
        buttonUserAccount.addActionListener(buttonListener);
    }
    
     public void addButtonSeeUserTransactionsListener(ActionListener buttonListener) {
        buttonSeeUserTransactions.addActionListener(buttonListener);
    }
     
      public void addButtonSeePricesListener(ActionListener buttonListener) {
        buttonSeePrices.addActionListener(buttonListener);
    }
      
       public void addButtonInsertMoneyListener(ActionListener buttonListener) {
        buttonInsertMoney.addActionListener(buttonListener);
    }
       
       public void addButtonLogOffListener(ActionListener buttonListener) {
        buttonLogUserOff.addActionListener(buttonListener);
    }
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonUserAccount = new javax.swing.JButton();
        buttonSeeUserTransactions = new javax.swing.JButton();
        buttonSeePrices = new javax.swing.JButton();
        buttonLogUserOff = new javax.swing.JButton();
        buttonInsertMoney = new javax.swing.JButton();

        buttonUserAccount.setText("Edit account");

        buttonSeeUserTransactions.setText("Transactions");

        buttonSeePrices.setText("See Prices");

        buttonLogUserOff.setText("Log off");

        buttonInsertMoney.setText("Insert Money");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonLogUserOff)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonUserAccount)
                        .addGap(18, 18, 18)
                        .addComponent(buttonSeeUserTransactions)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonSeePrices)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonInsertMoney)
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonLogUserOff)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonInsertMoney)
                    .addComponent(buttonSeePrices)
                    .addComponent(buttonSeeUserTransactions)
                    .addComponent(buttonUserAccount))
                .addContainerGap(203, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonInsertMoney;
    private javax.swing.JButton buttonLogUserOff;
    private javax.swing.JButton buttonSeePrices;
    private javax.swing.JButton buttonSeeUserTransactions;
    private javax.swing.JButton buttonUserAccount;
    // End of variables declaration//GEN-END:variables

}