/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Ibrahim
 */
public class CreatePricesViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePrices
     */
    public CreatePricesViewPanel() {
        initComponents();
    }

    public String getPriceLocation() {
        return textFieldLocation.getText();
    }

    public double getPriceDay() {
        String priceDay = textFieldPriceDay.getText();
        return Double.parseDouble(priceDay);
    }

    public double getPriceNight() {
        String priceNight = textFieldPriceNight.getText();
        return Double.parseDouble(priceNight);
    }

    public void setTextFieldLocation(String locationTextField) {
        this.textFieldLocation.setText(locationTextField);
    }

    public void setTextFieldPriceDay(String priceDayTextField) {
        this.textFieldPriceDay.setText(priceDayTextField);
    }

    public void setTextFieldPriceNight(String priceNightTextField) {
        this.textFieldPriceNight.setText(priceNightTextField);
    }
    

    public void addButtonCreatePricesListener(ActionListener buttonListnener) {
        buttonCreatePrices.addActionListener(buttonListnener);
    }
    
    public void addButtonBackListener(ActionListener buttonListnener) {
        buttonBack.addActionListener(buttonListnener);
    }
    
    public void displayErrorMessage(String errorMessage) {
        JOptionPane.showMessageDialog(this, errorMessage);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textFieldLocation = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textFieldPriceDay = new javax.swing.JTextField();
        textFieldPriceNight = new javax.swing.JTextField();
        buttonCreatePrices = new javax.swing.JButton();
        buttonBack = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jLabel2.setText("Location:");

        jLabel3.setText("Price Day:");

        jLabel4.setText("Price Night:");

        textFieldPriceNight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldPriceNightActionPerformed(evt);
            }
        });

        buttonCreatePrices.setText("Create Prices");
        buttonCreatePrices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreatePricesActionPerformed(evt);
            }
        });

        buttonBack.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(textFieldPriceNight, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2))
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(textFieldLocation, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                            .addComponent(textFieldPriceDay)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(buttonCreatePrices)))
                        .addGap(0, 160, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonBack)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textFieldLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textFieldPriceDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textFieldPriceNight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buttonCreatePrices)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(buttonBack)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    private void textFieldPriceNightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldPriceNightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldPriceNightActionPerformed
    private void buttonCreatePricesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreatePricesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCreatePricesActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonCreatePrices;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField textFieldLocation;
    private javax.swing.JTextField textFieldPriceDay;
    private javax.swing.JTextField textFieldPriceNight;
    // End of variables declaration//GEN-END:variables
}
