package View;

public class MainInterface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public MainInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        createCustomerViewPanel1 = new View.CreateCustomerViewPanel();
        editCustomerViewPanel1 = new View.EditCustomerViewPanel();
        seeTransactionsViewPanel2 = new View.SeeTransactionsViewPanel();
        createPricesViewPanel1 = new View.CreatePricesViewPanel();
        editPricesViewPanel1 = new View.EditPricesViewPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addTab("Create customer", createCustomerViewPanel1);
        jTabbedPane1.addTab("Edit customer", editCustomerViewPanel1);
        jTabbedPane1.addTab("See transactions", seeTransactionsViewPanel2);
        jTabbedPane1.addTab("Prices", createPricesViewPanel1);
        jTabbedPane1.addTab("Edit Prices", editPricesViewPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private View.CreateCustomerViewPanel createCustomerViewPanel1;
    private View.CreatePricesViewPanel createPricesViewPanel1;
    private View.EditCustomerViewPanel editCustomerViewPanel1;
    private View.EditPricesViewPanel editPricesViewPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private View.SeeTransactionsViewPanel seeTransactionsViewPanel2;
    // End of variables declaration//GEN-END:variables
   
    public SeeTransactionsViewPanel getSeeTransactionsViewPanel() {
        return seeTransactionsViewPanel2;
    }

    /**
     * @return the createCustomerPanel
     */
    public View.CreateCustomerViewPanel getCreateCustomerPanel() {
        return createCustomerViewPanel1;
    }

    /**
     * @return the editCustomerViewPanel1
     */
    public View.EditCustomerViewPanel getEditCustomerViewPanel() {
        return editCustomerViewPanel1;
    }
    
    public View.CreatePricesViewPanel getCreatePricesViewPanel(){
        return createPricesViewPanel1;
    }

    public View.EditPricesViewPanel getEditPricesViewPanel() {
        return editPricesViewPanel1;
        
    }

}
